version: "3.8"

services:

  postgres:
    image: postgres:16
    container_name: temporal-postgres
    environment:
      POSTGRES_USER: temporal
      POSTGRES_PASSWORD: temporal
      POSTGRES_DB: temporal
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  temporal:
    image: temporalio/auto-setup:1.28
    container_name: temporal
    depends_on:
      - postgres
    environment:
      DB: postgres12
      DB_PORT: 5432
      POSTGRES_USER: temporal
      POSTGRES_PWD: temporal
      POSTGRES_SEEDS: postgres
      #DYNAMIC_CONFIG_FILE_PATH: config/dynamicconfig/development.yaml
    ports:
      - "7233:7233"

  temporal-admin-tools:
    image: temporalio/admin-tools:1.28
    container_name: temporal-admin-tools
    depends_on:
      - temporal
    environment:
      TEMPORAL_ADDRESS: temporal:7233
    stdin_open: true
    tty: true

  temporal-ui:
    image: temporalio/ui:2.39.0
    container_name: temporal-ui
    depends_on:
      - temporal
    environment:
      TEMPORAL_ADDRESS: temporal:7233
      TEMPORAL_CORS_ORIGINS: http://localhost:3000
    ports:
      - "8233:8080"

volumes:
  postgres-data: